add case 5 and 6

diff --git a/.github/workflows/test-cm-based-submission-generation.yml b/.github/workflows/test-cm-based-submission-generation.yml
--- a/.github/workflows/test-cm-based-submission-generation.yml
+++ b/.github/workflows/test-cm-based-submission-generation.yml
@@ -19,7 +19,7 @@ jobs:
         python-version: [ "3.12" ]
         division: ["closed", "open", "closed-open"]
         category: ["datacenter", "edge"]
-        case: ["closed", "closed-no-compliance", "closed-power", "closed-failed-power-logs", "case-1", "case-2", "case-3", "case-7", "case-8"]
+        case: ["closed", "closed-no-compliance", "closed-power", "closed-failed-power-logs", "case-1", "case-2", "case-3", "case-5", "case-6", "case-7", "case-8"]
         action: ["run", "docker"]
         exclude:
           - os: macos-latest
@@ -33,8 +33,15 @@ jobs:
             division: closed
           - case: case-2
             division: closed-open
+          - case: case-5
+            division: closed
+          - case: case-5
+            division: closed-open
+          - case: case-6
+            division: closed
+          - case: case-6
+            division: closed-open
             
-          
     steps:
     - uses: actions/checkout@v4
     - name: Set up Python ${{ matrix.python-version }}
@@ -73,5 +80,17 @@ jobs:
         # Dynamically set the log group to simulate a dynamic step name
         echo "::group::$description"
         cm ${{ matrix.action }} script --tags=generate,inference,submission --adr.submission-checker-src.tags=_branch.dev --clean --preprocess_submission=yes --results_dir=$PWD/submission_generation_tests/${{ matrix.case }}/ --run-checker --submitter=MLCommons --tar=yes --env.CM_TAR_OUTFILE=submission.tar.gz --division=${{ matrix.division }} --env.CM_DETERMINE_MEMORY_CONFIGURATION=yes --quiet $extra_run_args
+        
+        if [[ "${{ matrix.case }}" -eq 5 || "${{ matrix.case }}" -eq 6 ]]; then
+          # For cases 5 and 6, exit status should be 0 if cm command fails, 1 if it succeeds
+          if [[ $exit_status -ne 0 ]]; then
+            exit 0
+          else
+            exit 1
+          fi
+        else
+          # For other cases, exit with the original status
+          test $exit_status -eq 0 || exit 1
+        fi
         echo "::endgroup::"
   
